name: Generate release

on: workflow_dispatch

jobs:
  generate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Get next release candidate
        run: |
          NEXT_RELEASE=$(grep 'version=' setup.py | sed 's/version="//' | sed 's/",//' | xargs)
          echo "NEXT_RELEASE=$NEXT_RELEASE" >> $GITHUB_ENV
        shell: bash

      - name: Create new minor release
        run: .github/scripts/release.py --release ${{ env.NEXT_RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update version in remote
        run: |
          git add setup.py
          git commit -m "chore: prepare next release candidate"
          git push

  publish-release:
    needs: generate-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Build release
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to Nexus
        run: |
          python -m twine upload --repository-url https://tnt.autentia.com/nexus/repository/autentia-pypi/ dist/*
