name: Generate release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history

      - name: "Configure Git User"
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Create new minor release
        run: .github/scripts/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update version in remote
        run: |
          git add setup.py
          git commit -m "chore: prepare new version"
          git push